### ISSUE TITLE
Need to update the marked lib dependency: Security issues patched

### ISSUE THREAD

**Issue by drpalaric** [IBM/marked-it#1]
Need to update the `marked` dependency to at lease >=0.3.9 or preferably the latest version (0.5.0 I believe). There are a few security issues that have been resolved.

**Comment by BigBlueHat** [comment]
I've submitted PR #3 fwiw. Would be great to get this merged. It's a great project, and I'd love to use it (unforked). 😄 Thanks!

**Comment by grant-g** [comment]
The dependency is updated in the latest, along with a corresponding change to handle incorrectly-but-previously-tolerated headers with incorrect syntax.

**Comment by grant-g** [comment]
Updated the mocha dependency as well, thanks for pointing this out in the PR.
