### ISSUE TITLE
update to a newer marked release

### ISSUE THREAD

**Issue by grant-g** [IBM/marked-it#11]
The current release is considered to be moderate risk according to https://github.com/IBM/marked-it/network/alerts.  Need to determine the HTML generation changes that were introduced between the currently-used release and this one.

**Comment by Simran-B** [comment]
FYI

![image](https://user-images.githubusercontent.com/7819991/68394777-be5cbb00-016e-11ea-8752-57f2556f95e4.png)

**Comment by grant-g** [comment]
Closing as WONTFIX, marked is no longer the md->HTML generator that's being used under the covers.
