### ISSUE TITLE
Ship a new npm release with the js-yaml fix

### ISSUE THREAD

**Issue by BigBlueHat** [IBM/marked-it#12]
`marked-it-core` is still triggering `npm audit` errors, but it looks like the vulnerable dependency (`js-yaml`) has been updated here but hasn't yet made it to NPM.

Would you mind shipping a new NPM version? 😺 

Could you also tag the versions in git when you ship stuff? That'd be super helpful for tracking down what's what where.

Thanks!
🎩

**Comment by grant-g** [comment]
This was done a while ago, so closing Issue.

I'll also make a habit of tagging in git, starting today :-).
