### ISSUE TITLE
Markdown extension coding for videos

### ISSUE THREAD

**Issue by jenschlot** [IBM/marked-it#21]
We should support both YouTube and "video". Leveraging the same idea used for the image captions in the accessibilityExt.js extension:

```
![Alt-Text](image.svg){: caption="Figure 1. A surprisingly tart visual that explains each Table of Contents metadata value." caption-side="bottom"}
```

Proposed Markdown coding for videos is to leverage the link syntax: 
```
[![IMAGE ALT TEXT HERE](VIDEO LINK){: video width="xx" height="xx"}
```
for example:
```
[![Watson Assistant product overview](https://www.youtube.com/embed/h-u-5f8fZtc?rel=0){: video width="640" height="390"}
```
```
[![Watson Assistant product overview](video.mp4){: video width="640" height="390"}
```

Based on the URL, marked-it would output to different HTML. If `youtube.com` was present in the video path, we'd output to recommended iFrame. If not, we'd output to `<video>`.

**YouTube output**
```
<iframe width="640" height="390"
title="Watson Assistant product overview"
src="https://www.youtube.com/embed/tgbNymZ7vqY?playlist=tgbNymZ7vqY&loop=1">
</iframe> 
```

**Video output**
```
 <video title="Watson Assistant product overview" width="640" height="390" controls>
  <source src="video.mp4" type="video/mp4">
Your browser does not support the video tag.
</video> 
```

**Comment by grant-g** [comment]
Added an extension that does this: https://github.com/IBM/marked-it-cli/commit/d6a81a11a6ba76d40b719f6c5135158563ccfbfe .
