### ISSUE TITLE
Is there a generic way to hide sections of the documentation (outside of IBM cloud doc hosting)

### ISSUE THREAD

**Issue by whowutwut** [IBM/marked-it#29]
I am looking for functionality similar to https://ibm.github.io/marked-it/mdSyntaxExtensions/attribute-hide/ where we can have the ability to hide a section of the documentation.

Currently we are rendering docs from internal GitHub repo to Knowledge Center.

For example,
* We are working on new features and want docs to be tied with code but the function is not yet released, we would want to hide this section until we GA the new features. 
* Anther scenario may be we want a branch to generate the PDF version of the doc which may include some sections we don't necessarily need in our web hosted docs.... in this case we could disable the content but enable it for the branch that we build the PDF off of. (??) 

Seems like the documentation above is for IBM cloud doc hosting?  Is there any generic tags that allows us to do something similar like that to hide/show doc content?

**Comment by whowutwut** [comment]
Anyone have any thoughts on this?  If there is no way to do this today, that is ok, please let me know. 

I am just looking for options before we commit sections to the doc that we really only want to be into a PDF, I guess we could work around this by creating a branch for PDF and only including those sections to that branch for generation.

**Comment by grant-g** [comment]
There isn't a way of getting marked-it to generate html containing code to hide sections.  In theory any custom generation could be added with a marked-it extension, but I don't think there are any such plans since the current approach is to just pass through the `hide-*` attributes for use by a subsequent process.

**Comment by whowutwut** [comment]
Thanks for the response! Will close this out.
