### ISSUE TITLE
investigate supporting footnotes

### ISSUE THREAD

**Issue by grant-g** [IBM/marked-it#9]
- https://www.markdownguide.org/extended-syntax/#footnotes
- https://raw.github.ibm.com/CloudEngineering/api_handbook/master/fundamentals/methods.md?token=AAAlJprgTIR-66b9V0jkfyJ2En2XfD4bks5dJOehwA%3D%3D

**Comment by jenschlot** [comment]
Footnotes are now available https://ibm.github.io/marked-it/#/footnotes
